### PR TITLE
Change nodemcu pinmap to hardware pinmap.

### PR DESCRIPTION
**Pull request by darkbyte-ru**
Now pin_mux and pin_func has indexes according to hardware GPIO pin numbers.
Currently pinmap using only i2c lib, so, to init i2c on GPIO0 and GPIO2 now write "i2c init 0 2"
"i2c init 3 4" will brake serial connection because GPIO 3 is UART RX pin.

Also remove ICACHE_FLASH_ATTR from functions headers and make minor fixes in i2c modules code. i2c modules, that not fully tested was removed from config to avoid compile it by mistake.

### CODE REVIEW

**Comment by nekromant** [comment]
Looks like there are some conflicts out there, can you fix them? 
And instead of removing stuff from kcnf just default to 'n' and add (untested) to their names. Just in case someone wants to test and report a problem.

**Comment by darkbyte-ru** [comment]
I see that there is conflicts, but I can't find where I can see which files was conflicting. Seems that is because @pastcompute also make changes in files that I change, but after this commit his changes is useless, so you can override it or revert merge in pull request #44.

**Comment by nekromant** [comment]
@darkbyte-ru Got it. I'll merge it manually in the evening then, when I get to the actual hardware.

**Comment by nekromant** [comment]
Your pull request has too much unrelated changes, most are conflicting. Can you resubmit it against current git master with only pin_map changes?

**Comment by darkbyte-ru** [comment]
Yep, I create another pull request, which has no conflicts. Next time try to solve conflicts before creating pull request, sorry.

**Pull request closed without merging**
