### PR TITLE
Some fixes for i2c support

### PR DESCRIPTION
**Pull request by darkbyte-ru**
Added: MLX90614, HMC5883
Fixed: SHT21, BMP180, PCF8591
Additional info in commit history. Last demo: 

frankenstein > i2c init 3 4
Init i2c bus on 3:4 pins

frankenstein > i2c scan
Enumeration i2c bus...

Found device on 0x46. BH1750?
Found device on 0x78. SSD1306 OLED?
Found device on 0x80. SHT21? HTU21?
Found device on 0x90. PCF8591?
Found device on 0xa0. EEPROM? DS1337?
Found device on 0xa6. ADXL345?
Found device on 0xae. DS3231SN?
Found device on 0xb4. MPR121? MLX90614?
Found device on 0xd0. DS1337?
Found device on 0xee. BMP180? BMP085?

frankenstein > i2c_bmp180 init
Ok

frankenstein > i2c_bmp180 read
Temperature: 317 C
Pressure: 75177 mmHg

frankenstein > i2c_bmp180
317 75177

frankenstein > i2c_sht21 init
Ok

frankenstein > i2c_sht21 read
Temperature: 3070 C
Humidity: 1889 %

frankenstein > i2c_pcf8591 init
Ok

frankenstein > i2c_pcf8591 read
A0-A3: 98 98 205 127

frankenstein > i2c_pcf8591 write 255
Ok
frankenstein > i2c_pcf8591 write 0
Ok

frankenstein > i2c_bh1750 init
Ok

frankenstein > i2c_bh1750 read
Light: 376 lux

### CODE REVIEW

**Comment by d-a-v** [comment]
Hello,

For all your i2c commands, is "init" subcommand mandatory in command line?
Could all i2c commands integrate init directly in the "read" or "" subcommand ?

logs would become:

frankenstein > i2c init 3 4
Init i2c bus on 3:4 pins

frankenstein > i2c scan
Enumeration i2c bus...

Found device on 0x46. BH1750?
Found device on 0x78. SSD1306 OLED?
Found device on 0x80. SHT21? HTU21?
Found device on 0x90. PCF8591?
Found device on 0xa0. EEPROM? DS1337?
Found device on 0xa6. ADXL345?
Found device on 0xae. DS3231SN?
Found device on 0xb4. MPR121? MLX90614?
Found device on 0xd0. DS1337?
Found device on 0xee. BMP180? BMP085?

frankenstein > i2c_bmp180 read
Temperature: 317 C
Pressure: 75177 mmHg

frankenstein > i2c_bmp180
317 75177

frankenstein > i2c_sht21 read
Temperature: 3070 C
Humidity: 1889 %

frankenstein > i2c_pcf8591 read
A0-A3: 98 98 205 127

[...]

**Comment by darkbyte-ru** [comment]
d-a-v, currently "init" command is mandatory. For some devices "init" was useless and check only that device online (ex: sht21, bh1750, pcf8591), but for some devices reading without init may crash chip (ex: bmp180). 

Make autoinitialization will be great, but there is one problem, that I can't solve. How to check that device already initialized? For TCS3414 I can check that ADC is enabled, but for BMP180 I need read calibration constants which is differ from chip to chip, so if user make initialization with one bmp180 chip and replace it with other, readed values was false.

Maybe do autoinitialization once and also allow user to make reinitialization manually? Or there is better way?

**Comment by d-a-v** [comment]
On lun., mars 16, 2015 at 05:05:13 -0700, DarkByte wrote:
>
> d-a-v, currently "init" command is mandatory. For some
> devices "init" was useless and check only that device online
> (ex: sht21, bh1750, pcf8591), but for some devices reading
> without init may crash chip (ex: bmp180).
> 
> Make autoinitialization will be great, but there is one
> problem, that I can't solve.  How to check that device
> already initialized?  For TCS3414 I can check that ADC is
> enabled, but for BMP180 I need read calibration constants
> which is differ from chip to chip, so if user make
> initialization with one bmp180 chip and replace it with
> other, readed values was false.

I was thinking of a static variable in each of your drivers,
inside the per-chip-read command.  0 at first call means init
must be done.

> Maybe do autoinitialization once and also allow user to make
> reinitialization manually?  Or there is better way?

Yes: autoinitialization at first call.
I'm not aware of all chips requirements, I may be wrong thinking
this is possible.

david

**Comment by darkbyte-ru** [comment]
Ok, I will do it, thanks!

**Comment by nekromant** [comment]
Maybe you can use environment to describe attached devices? 
e.g. setenv i2c_devices "bmp180:2,3,0xee;sht21"

Sorry, can't have a proper look at the code and give it a spin - another deadline fast approaching.

**Comment by darkbyte-ru** [comment]
nekromant, I see two problems here:
1) In my case environment is not stable. Sometimes after flash or reboot i got error: "env: Bad CRC (de40 vs bc01) using defaults". It happens with all 15 esp's that I have. For module power I use 3.7-4.2 LiIon cell with AMS1117 regulator (with ceramic and electrolyte capacitors), so I have stable 3.3V at 1A that was be enough for one module.
But when/if env be stable, I would make some variables for pereodic read values from sensors and do something, for ex. send it to remote service.

2) i2c devices may have differ address depend of it settings, but currently drivers support only fixed address defined in constant. It is not a problem in really, it's TODO :)

**Comment by nekromant** [comment]
Hm... Can you try dumping the data from env block after corruption happens? Espressif folks store wireless passwords in plaintext in the last blocks. These may change from SDK version to version.  Maybe they have relocated their setting's address. If that's the issue - you'll lose environment whenever you connect to an AP and specify a password. 
Solution would be saving environment to a different offset in flash (See menuconfig)

**Comment by darkbyte-ru** [comment]
Yep, after iwconnect on address 0x7f000 all data was erased by FF, except part of crc and length of the list. Which address you suggest to use instead for ENV_OFFSET?

**Comment by nekromant** [comment]
A good question, try nearby adresses to see of they are occupied. There's a CMD for that that checks what blocks have been altered by blobs.

**Comment by darkbyte-ru** [comment]
frankenstein > flash_scan
Sector 124 (0x7c000) has been tampered by blobs
Sector 125 (0x7d000) has been tampered by blobs
Sector 126 (0x7e000) has been tampered by blobs
Sector 127 (0x7f000) has been tampered by blobs

**Comment by darkbyte-ru** [comment]
Address 0x7c000 almost empty (128 bytes from start was filled), 0x7d000 and 0x7e000 contain wifi configuration and 7f000 was full empty (except first 4 bytes). I moved env to 0x7C800 and truncated to 2048 bytes. iwconfig now does not overwrite it.

**Comment by nekromant** [comment]
Align environment to flash erase size (4k if I remember correct). For when saving env it will erase everything in that block anyway.

**Comment by darkbyte-ru** [comment]
Hm, strange. I write env to 7C800 and seems that full block was erased, but then I write env to 7C000 and old env on 7C800 was not erased, but it is in the same 4k block. iwconnect does not overwrite 7C000, I will continue test env on this address.

**Comment by d-a-v** [comment]
Hi,
There are missing symbols for HMC5884l : undefined reference to i2c_master_readRegister16 i2c_master_readRegister8 and i2c_master_writeRegister with current master.

**Comment by darkbyte-ru** [comment]
Oh, it was a bad idea to delete unused functions from i2c master lib and do not do test compilation with all enabled i2c modules. I got a strange bug, so decide disable module HMC5884l and set disabled by default in config. Firmware with builded HMC5884l support does not boot up, bootloader says about CRC error. Today I will try to fix it, or comment out entry module for the future fix.

**Comment by d-a-v** [comment]
On jeu., mars 19, 2015 at 02:33:12 -0700, DarkByte wrote:
> Oh, it was a bad idea to delete unused functions from i2c master lib and do not do test compilation with all enabled i2c modules. I got a strange bug, so decide disable module HMC5884l and set disabled by default in config. Firmware with builded HMC5884l support does not boot up, bootloader says about CRC error. Today I will try to fix it, or comment out entry module for the future fix.

No problem for me, master is not intended to be always stable :)

**Pull request merged**
