### PR TITLE
I2C menu for test connected devices

### PR DESCRIPTION
**Pull request by darkbyte-ru**
Currently tested with BMP180, BMP085, SHT21, BH1750, PCF8591.
Not tested: TCS3414, HMC5883, HD44780.

Usage example (pins 3:4 mean GPIO0:GPIO2 according to pin_map.c):
> i2c init 3 4
Init i2c bus on 3:4 pins 

> i2c scan
Enumeration i2c bus...

Found device on 0x3c. HMC5883L?
Found device on 0x46. BV1750? yes!
Light: 6825 lux

Found device on 0x78. OLED?
Found device on 0x80. SHT21? yes!
Temperature: 28156
Humidity: 18428

Found device on 0x90. PCF8591? yes!
A0-A3: 128 192 0 0

Found device on 0x92. Unknown device.
Found device on 0x94. Unknown device.
Found device on 0xa0. EEPROM?
Found device on 0xa6. ADXL345?
Found device on 0xae. DS3231SN?
Found device on 0xb4. MPR121?
Found device on 0xd0. DS1337?
Found device on 0xd2. L3G4200D?
Found device on 0xee. BMP180? yes!
Temperature: 77
Pressure: 56457

### CODE REVIEW

**Comment by d-a-v** [comment]
Great!

**Comment by nekromant** [comment]
Hm, looks great, but coupling i2c scan command with actually identifying/reading devices is not a good idea. Some devices out there in the wild can misbehave. Especially some super-dumb cheap i2c-to-gpio expander chips. Besides - there are a ton of i2c devices out there, many with the same addresses. 
Can you refactor it the following way?  
* Make i2c scan only output detected addresses, but not actually try to read anything from the detected sensors. 
* Move reading of each of the sensors you've added to a dedicated CONSOLE_CMD that can be enabled/disabled

**Comment by darkbyte-ru** [comment]
Sounds reasonable, I will do.

**Comment by darkbyte-ru** [comment]
I make changes, new example of usage:

frankenstein > i2c init 4 3
Init i2c bus on 4:3 pins

frankenstein > i2c scan
Enumeration i2c bus...

Found device on 0x46. BV1750?
Found device on 0x80. SHT21? HTU21?
Found device on 0xee. BMP180? BMP085?

frankenstein > i2c_bmp180 init
Ok

frankenstein > i2c_bmp180 read
Temperature: 220
Pressure: 89692

frankenstein > i2c_bmp180
220 89692

**Pull request merged**
