### PR TITLE
Add instructions for manually flashing, and option to change PORT

### PR DESCRIPTION
**Pull request by pastcompute**
I dont have a pl2303 breakout so I added instructions on flashing manually, also added easy method to change the default tty port to use

### CODE REVIEW

**Comment by pastcompute** [comment]
Please hold of merging a bit, I may not have tested all edge cases...

**Comment by pastcompute** [comment]
OK, sorted it something went wrong when I merged upstream

**Comment by nekromant** [comment]
The flashing targets in top level makefile are obsolete for a little while. esptool.py is now a valid 'deployment' method in antares. 
See antares/deploy/esptool/

It is invoked by make deploy-esptool and configured via menuconfig under 'Deployment' section

**Comment by pastcompute** [comment]
No worries

**Pull request closed without merging**
